mixed-port: 10801
bind-address: "*"
mode: rule
log-level: debug
find-process-mode: strict
global-client-fingerprint: chrome
allow-lan: true
ipv6: true
tcp-concurrent: true
enable-process: true
unified-delay: true
keep-alive-interval: 30

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true
  strict-route: true

dns:
  enable: true
  listen: :1053
  prefer-h3: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  nameserver:
    - 'https://1.1.1.2/dns-query#PROXY&h3=true'
    - 'https://1.1.1.2/dns-query#PROXY'
  proxy-server-nameserver:
    - 'https://1.1.1.2/dns-query'

{{ conf | except("proxy-groups", "port", "mode", "rules") | yaml }}

proxy-groups:
- name: 'PROXY'
  type: 'select'
  proxies:
  - '📶 First Available'
  - '⚡️ Fastest'
  - '♻️ Load Balance'
  {{ proxy_remarks | yaml | indent(2) }}

- name: '📶 First Available'
  type: 'fallback'
  url: 'https://cp.cloudflare.com/generate_204'
  interval: 180
  max-failed-times: 2
  lazy: false
  proxies:
  {{ proxy_remarks | yaml | indent(2) }}

- name: '⚡️ Fastest'
  type: 'url-test'
  url: 'https://cp.cloudflare.com/generate_204'
  interval: 180
  tolerance: 50
  max-failed-times: 2
  lazy: false
  proxies:
  {{ proxy_remarks | yaml | indent(2) }}

- name: '♻️ Load Balance'
  type: 'load-balance'
  url: 'https://cp.cloudflare.com/generate_204'
  interval: 180
  max-failed-times: 2
  strategy: 'sticky-sessions'
  lazy: false
  proxies:
  {{ proxy_remarks | yaml | indent(2) }}

rule-providers:
  ir:
    type: http
    format: text
    behavior: domain
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt"
    path: ./ruleset/ir.txt
    interval: 86400
  ads:
    type: http
    format: text
    behavior: domain
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/category-ads-all.txt"
    path: ./ruleset/category-ads-all.txt
    interval: 86400
  malware:
    type: http
    format: text
    behavior: domain
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.txt"
    path: ./ruleset/malware.txt
    interval: 86400
  phishing:
    type: http
    format: text
    behavior: domain
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/phishing.txt"
    path: ./ruleset/phishing.txt
    interval: 86400
  cryptominers:
    type: http
    format: text
    behavior: domain
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/cryptominers.txt"
    path: ./ruleset/cryptominers.txt
    interval: 86400
  apps:
    type: http
    format: text
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/apps.txt"
    path: ./ruleset/apps.txt
    interval: 86400
  ircidr:
    type: http
    format: text
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt"
    path: ./ruleset/ircidr.txt
    interval: 86400
  private:
    type: http
    format: text
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/private.txt"
    path: ./ruleset/private.txt
    interval: 86400
  irasn:
    type: http
    format: text
    behavior: classical
    url: "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.txt"
    path: ./ruleset/irasn.txt
    interval: 86400

rules:
  - RULE-SET,private,DIRECT,no-resolve
  - RULE-SET,apps,DIRECT
  - RULE-SET,ir,DIRECT
  - RULE-SET,ircidr,DIRECT
  - RULE-SET,irasn,DIRECT
  - DOMAIN-KEYWORD,snapdrop,DIRECT
  - DOMAIN-KEYWORD,pairdrop,DIRECT
  - RULE-SET,ads,REJECT
  - RULE-SET,malware,REJECT
  - RULE-SET,phishing,REJECT
  - RULE-SET,cryptominers,REJECT
  - IP-CIDR,10.10.34.0/24,PROXY
  - MATCH,PROXY
